title: scratch3-sprite-direction
hero_image: images/banner.png
description: scratch3-sprite-direction description
version: 4
listed: false
copyedit: false
last_tested: "2021-06-10"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
